config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions, only: [:index, :show, :create, :new, :edit, :update]
  resources :answers, only: [:show, :create, :new]

  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :answer, presence: true
  validates :question_id, presence: true
  validates :user_id, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  validates :question_name, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController


  def show
    @question = Question.find(params[:question_id])
  end

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @question_id = params[:question_id]
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question_id = @question_id

    if @answer.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer, :user_id, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.where question_id: params[:id]

  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      render :new
    end
  end


  private

  def question_params
    params.require(:question).permit(:question_name, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<h1>Answers For</h1>


<%= form_for [@question, @answer] do |f|%>
<div>
  <%= f.label :answer %>
  <%= f.text_field :answer %>
</div>

<div>
  <%= f.label :user_id %>
  <%= f.text_field :user_id %>
</div>

<div>
  <%= f.submit 'Submit' %>
</div>
<% end %>

app/views/answers/show.html.erb
<h1>Individual A-sers</h1>



  <h4>Answer</h4>
  <% @answer.each do |a| %>
  <p> <%= a.user_id %> </p>
  <p> <%= a.answer %> </p>
    <% end %>

<!-- <p><%= link_to "Question", question_path(@question)%></p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Questions</h1>

  <%= form_for @question do |f|%>
   <div>
     <%= f.label :question_name %>
     <%= f.text_field :question_name %>
   </div>

   <div>
     <%= f.label :description %>
     <%= f.text_area :description %>
   </div>

   <div>
     <%= f.label :user_id %>
     <%= f.text_field :user_id %>
   </div>

   <div>
     <%= f.submit 'Update' %>
   </div>

     <% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <h3><%= link_to question.question_name, question_path(question.id) %></h3>
  <p><%= question.description %></p>
  <% end %>

app/views/questions/new.html.erb
<h1>new Questions</h1>

  <%= form_for @question do |f|%>
   <div>
     <%= f.label :question_name %>
     <%= f.text_field :question_name %>
   </div>

   <div>
     <%= f.label :description %>
     <%= f.text_area :description %>
   </div>

   <div>
     <%= f.label :user_id %>
     <%= f.text_field :user_id %>
   </div>

   <div>
     <%= f.submit 'Submit' %>
   </div>

     <% end %>

app/views/questions/show.html.erb
<h1>Individual Q-tions</h1>

  <h3><%= @question.question_name %></h3>
  <p>Description: <%= @question.description %></p>
  <p>By: <%= @question.user_id %></p>


  <h4>Answers</h4>
  <% @answer.each do |a| %>
  <p> <%= a.user_id%> this guy knows the answer: </p>
  <p> <%= a.answer %> </p>
    <% end %>

<p><%= link_to "Answer This Question", new_question_answer_path(@question)%></p>
<p><%= link_to "Edit", edit_question_path(@question)%></p>